language: go
go: '1.7'
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.24.1/hugo_0.24.1_Linux-64bit.tar.gz
- tar xzf hugo_0.24.1_Linux-64bit.tar.gz
- export PATH=$PATH:$PWD
script: ./bin/build
deploy:
  provider: cloudfoundry
  skip_cleanup: true
  api: https://api.run.pivotal.io
  username: engineering-blog@pivotal.io
  organization: pivotal
  space: blog
  on:
    repo: pivotal/blog
    branch: master
  password:
    secure: WHwkaU/iMcqxj0j60hdmj07hjKsBsw35JWzIlgx/kZoR9ZJPsCraGiBOxw2gtd63tRL9tDg/G4BMJ9PaErTdCWFdopf8X/aoIjPt9FcmynIxYqU4vnxgPOsSxgfKjjVf8SGE0bLofvHHYNT43SCgyCT6T7VfwwGouMifR7fNQQ6KqHbPoa6wNEAYd+QiOe8o0iomPj9BxPjyg+Fe5WrpJxzcBzXZ2Mdv02ylwdV2P6jvgDOg89EEdUwlpWazJyx3TYAtHcagUpB8GQSAw0+SP6NpYcVFKiABAZmNLugw3Jo6kp4rL4/MJOFnanmI3nqPerShOA+M3EZ8ZKrP4g8K9i5Bnz500Jy0P7gEQ+cOYoa1YaZeUNsA2l0GJY5X8Pn4f+hrJfY0JwJw2EwLky5iMEaYuXhCb5nri0HDZwUWkbm5ZHxBN7I4woOpSKtvLETb+w4lYLKv9rKt+CRN1taXFU5gjBgz1nMDcO7wSv9hF4LyKeM9wzMjcI0rBszThZqq2YJPQ92V9lvIvDR96CfkZgkUUG9halpy0apHusk/CEWpksvexvNHqjQFnHN7FTy5EJZWepkheyF7QlQ9sRIeL7rELVU/WM3WJ3fXmcFyPdbjuI7B5ZtKZKJF7zidyEwSJlaLwXPnNvGKqWZ47oYZmaGCo63UT4wIoHh0fB21p4E=
notifications:
  slack:
    secure: gzsa/wyD5IE/9Mzao33A4jtyPbqu3UI7cE3RaWy3i04G5U+7zmVIurpxlMMhp62RmKpr0r40suKJ40F3tRn2/FQbqpWZ39MWkfP8DNg0JDGHLOsG6HpuAC8dwSAs1TrnK+K/L+zzKJzGPEnZ/vhymMtC4htkLPCtwJTvomo6RCTFAc4F/S49EdD/6S/A7AATrOrSOWjZ8nfM71/lF6OvwmODVVGk0C2vg4kFE2W3icQaoSJ2dkO5Y1vgHSXtivXmvHG7y5MCDVHnwyxgWN7e1l5ELTVNHP8v9DxUBTN6ILtaBwpy1R3G6997TPJEGVfaAEek0pUpbNpXg4Pv6Cirmq1byoBOx693DUmyZRqOWGhg9yHicNr2AM3dc7eVpoD+ckeqmbgnX53sPd5eSlntbRys9YqdF0TVlkuOK40valUwBeo7bNsD7gU5hkXRI/v0pVUNODJbnVi43vsY6zCcSek2phi0hvwnI1t2toy8w6d2HuwkSq3czOkJPuzUhQhnqZASdZTUmTyymaPlEwVfv5M4956WMA3Zg75WcunYzB2E18Kp6DYA3CSRV3NCT8P6HFysOX0lpvHEDXl6S1weWkpbK+lXkrYkyhrV4uim+b+49g+kqgJpuHmhCyLlxMXlI3Dzb7Rn6MMKLJCwxjmenoqm6/LsJY7jdkwz2ojYfvs=
